// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Biblioteca_De_Clases.galaxia", b =>
                {
                    b.Property<string>("codigo_galaxia")
                        .HasColumnType("TEXT");

                    b.Property<int>("edad_millones_años_galaxia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre_galaxia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("codigo_galaxia");

                    b.ToTable("galaxia");
                });

            modelBuilder.Entity("Biblioteca_De_Clases.luna", b =>
                {
                    b.Property<string>("codigo_luna")
                        .HasColumnType("TEXT");

                    b.Property<double>("distancia_km_planeta_luna")
                        .HasColumnType("REAL");

                    b.Property<int>("edad_años_luna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre_luna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("planeta_lunacodigo_planeta")
                        .HasColumnType("TEXT");

                    b.HasKey("codigo_luna");

                    b.HasIndex("planeta_lunacodigo_planeta");

                    b.ToTable("luna");
                });

            modelBuilder.Entity("Biblioteca_De_Clases.planeta", b =>
                {
                    b.Property<string>("codigo_planeta")
                        .HasColumnType("TEXT");

                    b.Property<double>("densidad_planeta")
                        .HasColumnType("REAL");

                    b.Property<int>("edad_años_planeta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("galaxia_planetacodigo_galaxia")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre_planeta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("volumen_planeta")
                        .HasColumnType("REAL");

                    b.HasKey("codigo_planeta");

                    b.HasIndex("galaxia_planetacodigo_galaxia");

                    b.ToTable("planeta");
                });

            modelBuilder.Entity("Biblioteca_De_Clases.luna", b =>
                {
                    b.HasOne("Biblioteca_De_Clases.planeta", "planeta_luna")
                        .WithMany("lunas_planeta")
                        .HasForeignKey("planeta_lunacodigo_planeta");

                    b.Navigation("planeta_luna");
                });

            modelBuilder.Entity("Biblioteca_De_Clases.planeta", b =>
                {
                    b.HasOne("Biblioteca_De_Clases.galaxia", "galaxia_planeta")
                        .WithMany("planetas_galaxia")
                        .HasForeignKey("galaxia_planetacodigo_galaxia");

                    b.Navigation("galaxia_planeta");
                });

            modelBuilder.Entity("Biblioteca_De_Clases.galaxia", b =>
                {
                    b.Navigation("planetas_galaxia");
                });

            modelBuilder.Entity("Biblioteca_De_Clases.planeta", b =>
                {
                    b.Navigation("lunas_planeta");
                });
#pragma warning restore 612, 618
        }
    }
}
